backend:
  name: git-gateway

media_folder: '/static/assets'
public_folder: '/assets'
<<<<<<< HEAD
=======
publish_mode: editorial_workflow
>>>>>>> def8cce... add i like avery

collections:
  - name: blog
    label: poem
    folder: src
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }